### PR TITLE
Added hyper plugin

### PR DESCRIPTION
**Pull request by dimitrieh**
@ealeksandrov could you test this out for me? and if it works, push a new release? :)

### CODE REVIEW

**Comment by tghs** [comment]
The plugin works fine for me, Dimitrie.

Some bits needing work (roughly in order):
* [x] Drop plugins/hyper/osaglue. Looks like cruft left over from iterm plugin template.
* [x] Rename plugins/hyper/iterm.xcodeproj -> plugins/hyper/hyper.xcodeproj.
* [x] cd_to.xcodeproj: Add hyper.xcodeproj under "external projects" group.
* [x] cd_to.xcodeproj: "cd_to all" target: Add the hyper bundle in the target dependencies.
* [x] cd_to.xcodeproj: "cd_to all" target: Add the pair of copy files phases for hyper.
* [x] cd_to.xcodeproj: "cd_to all" target: Add hyper to the "Sign apps" run script phase.

**Comment by dimitrieh** [comment]
@tghs thanks! I changed the first 2 points you made. Would you be able to change the specific xcode points, as I am not familiar with the software ;)

if you cannot (because of permissions), i could copy your changes in to my branch, from your fork

**Comment by tghs** [comment]
@dimitrieh Sure. I'll submit it as a PR against your branch, which should show up here after you accept it into your branch.

**Comment by dimitrieh** [comment]
@tghs thanks! merged it in! 

@ealeksandrov ready to be merged and released ;)

**Comment by ealeksandrov** [comment]
Thanks guys! Will look into this on weekend.

**Comment by ealeksandrov** [comment]
I still remember about this, will play with Hyper on this Sunday/Monday, sorry for delay, busy on work.

**Comment by ealeksandrov** [comment]
Works great, thanks! Releasing 2.8.0 :shipit:

**Comment by ealeksandrov** [comment]
Released: https://github.com/ealeksandrov/cdto/releases/tag/2_8_0 🎉
Thanks @dimitrieh and @tghs!

**Comment by dimitrieh** [comment]
Works like a charm!

**Pull request merged**
